#!/usr/bin/env python3
"""
Build the AI-Ready Banking white paper PDF.
Pipeline: HTML (single source of truth) -> html.parser -> fpdf2 typesetting.
No browser, no external services. Pure Python.

Usage: python _build_pdf.py
"""
import html as htmlmod
import os
import re
from html.parser import HTMLParser

from fpdf import FPDF
from fontTools.ttLib import TTFont

ROOT = os.path.dirname(os.path.abspath(__file__))
SRC = os.path.join(ROOT, "white-papers", "core-pillars-of-ai-ready-banking.html")
OUT = os.path.join(ROOT, "white-papers", "core-pillars-of-ai-ready-banking.pdf")
FONT_DIR = os.path.join(ROOT, "assets", "fonts")
TTF_DIR = os.path.join(FONT_DIR, "ttf")

PW, PH = 210, 297  # A4, mm
ML, MR, MT, MB = 18, 18, 20, 22
BODY_W = PW - ML - MR

INK = (16, 27, 40)
NAVY = (13, 27, 42)
GOLD = (143, 97, 24)
GOLD_LT = (200, 164, 92)
MUTE = (95, 109, 122)
RULE = (216, 221, 227)
PAPER_TINT = (243, 245, 247)


# ---------------- fonts: statics generated by make_fonts (see _build_pdf.py) ----------------

STATIC = {
    "": ("newsreader-400", "assets/fonts/static/newsreader-400.ttf"),
    "B": ("newsreader-600", "assets/fonts/static/newsreader-600.ttf"),
    "I": ("newsreader-i400", "assets/fonts/static/newsreader-i400.ttf"),
    "D": ("newsreader-display", "assets/fonts/static/newsreader-display.ttf"),
}


def ensure_ttf(style):
    _, path = STATIC[style]
    return os.path.join(ROOT, path)


# ---------------- content: parse the HTML ----------------

class PaperParser(HTMLParser):
    def __init__(self):
        super().__init__()
        self.blocks = []
        self.open = []
        self.list_stack = None

    def handle_starttag(self, tag, attrs):
        cls = dict(attrs).get("class", "")
        if tag in ("h2", "h3"):
            b = {"tag": tag, "text": ""}
        elif tag == "p":
            b = {"tag": "p", "text": "", "cls": cls}
        elif tag == "li":
            b = {"tag": "li", "text": ""}
        elif tag in ("ul", "ol"):
            b = {"tag": "list", "ordered": tag == "ol", "items": []}
            self.blocks.append(b)
            self.list_stack = b
            return
        elif tag == "div" and "colophon" in cls:
            b = {"tag": "colophon", "text": ""}
        elif tag == "br":
            if self.open:
                self.open[-1]["text"] += " "
            return
        elif tag in ("strong", "b"):
            if self.open:
                self.open[-1]["text"] += "**"
            return
        elif tag in ("em", "i"):
            if self.open:
                self.open[-1]["text"] += "*"
            return
        else:
            return
        self.blocks.append(b)
        self.open.append(b)

    def handle_endtag(self, tag):
        if tag in ("strong", "b"):
            if self.open:
                self.open[-1]["text"] += "**"
        elif tag in ("em", "i"):
            if self.open:
                self.open[-1]["text"] += "*"
        elif tag == "li":
            if self.open and self.list_stack is not None:
                item = self.open.pop()
                self.list_stack["items"].append(item["text"].strip())
        elif tag in ("h2", "h3", "p", "div"):
            if self.open:
                self.open.pop()
        elif tag in ("ul", "ol"):
            self.list_stack = None

    def handle_data(self, data):
        if self.open:
            self.open[-1]["text"] += data


def clean(s):
    return re.sub(r"\s+", " ", htmlmod.unescape(s)).strip()


def parse(src):
    p = PaperParser()
    p.feed(open(src, encoding="utf-8").read())
    out = []
    for b in p.blocks:
        if b["tag"] in ("h2", "h3"):
            t = clean(b["text"])
            num = ""
            m = re.match(r"^(\d+)\s*", t)
            if m:
                num, t = m.group(1), t[m.end():]
            out.append({"tag": b["tag"], "num": num, "text": t})
        elif b["tag"] == "p":
            cls = b.get("cls", "")
            kind = "lede" if "lede" in cls else ("box" if "box" in cls else ("boxlabel" if "box-label" in cls else "p"))
            out.append({"tag": "p", "kind": kind, "text": clean(b["text"])})
        elif b["tag"] == "colophon":
            out.append({"tag": "colophon", "text": clean(b["text"])})
        elif b["tag"] == "list":
            out.append({"tag": "list", "ordered": b["ordered"], "items": [clean(i) for i in b["items"]]})
    return out


# ---------------- the PDF ----------------

class PaperPDF(FPDF):
    def __init__(self):
        super().__init__(format="A4", unit="mm")
        self.compress = True
        self._box_label = ""

    def footer(self):
        if self.page_no() <= 1:
            return
        self.set_y(PH - MB + 4)
        self.set_font("Newsreader", "", 8.5)
        self.set_text_color(*MUTE)
        self.cell(0, 5, str(self.page_no()), align="R")

    def rule(self, thick=0.3):
        self.set_fill_color(*RULE)
        self.rect(ML, self.get_y(), BODY_W, thick, style="F")
        self.ln(0.8)

    def emit(self, blk):
        tag = blk["tag"]
        if tag == "h2":
            if self.get_y() > PH - MB - 42:
                self.add_page()
            self.ln(7)
            x0 = ML
            self.set_font("Newsreader", "B", 15)
            if blk["num"]:
                self.set_text_color(*GOLD)
                self.set_x(x0)
                self.cell(9, 7, blk["num"], new_x="RIGHT", new_y="TOP")
            self.set_text_color(*INK)
            self.multi_cell(BODY_W - 9, 7, blk["text"], new_x="LEFT", new_y="NEXT")
            self.ln(1.5)
            self.rule()
            self.ln(3.2)
        elif tag == "h3":
            if self.get_y() > PH - MB - 34:
                self.add_page()
            self.ln(4.5)
            self.set_font("Newsreader", "B", 12)
            self.set_text_color(*INK)
            self.multi_cell(BODY_W, 6, blk["text"], new_x="LEFT", new_y="NEXT")
            self.ln(1.8)
        elif tag == "p":
            self.paragraph(blk)
        elif tag == "list":
            self.emit_list(blk)
        elif tag == "colophon":
            self.emit_colophon(blk["text"])

    def paragraph(self, blk):
        kind = blk.get("kind", "p")
        if kind == "lede":
            if self.get_y() > PH - MB - 42:
                self.add_page()
            self.ln(2.5)
            y0 = self.get_y()
            self.set_font("Newsreader", "I", 13)
            self.set_text_color(60, 74, 90)
            self.multi_cell(BODY_W - 8, 7, blk["text"], new_x="LEFT", new_y="NEXT")
            self.set_fill_color(*GOLD)
            self.rect(ML - 2, y0, 1.1, self.get_y() - y0, style="F")
            self.ln(3.2)
        elif kind == "p":
            self.set_font("Newsreader", "", 10.5)
            self.set_text_color(*INK)
            self.multi_cell(BODY_W, 5.3, blk["text"], markdown=True, new_x="LEFT", new_y="NEXT")
            self.ln(1.6)
        elif kind == "boxlabel":
            self._box_label = blk["text"]
        elif kind == "box":
            self.emit_box(blk["text"])

    def emit_box(self, body):
        label = self._box_label
        self._box_label = ""
        if self.get_y() > PH - MB - 62:
            self.add_page()
        self.ln(2.5)
        pad = 5
        inner_w = BODY_W - 2 * pad
        y0 = self.get_y() + 1.5
        # measure content
        h_label = 0
        if label:
            self.set_font("Newsreader", "B", 9)
            h_label = self.multi_cell(inner_w, 4.8, label, dry_run=True, output="HEIGHT")
        self.set_font("Newsreader", "", 10.3)
        h_body = self.multi_cell(inner_w, 5.1, body, dry_run=True, output="HEIGHT")
        box_h = 2 + (h_label + 1.2 if label else 0) + h_body + 2
        # paint
        self.set_fill_color(*PAPER_TINT)
        self.set_draw_color(*RULE)
        self.rect(ML, y0, BODY_W, box_h, style="DF")
        yy = y0 + 2
        if label:
            self.set_y(yy)
            self.set_font("Newsreader", "B", 9)
            self.set_text_color(*GOLD)
            self.multi_cell(inner_w, 4.8, label, new_x="LEFT", new_y="NEXT")
            self.ln(1.2)
            yy = self.get_y()
        self.set_y(yy)
        self.set_font("Newsreader", "", 10.3)
        self.set_text_color(*INK)
        self.multi_cell(inner_w, 5.1, body, markdown=True, new_x="LEFT", new_y="NEXT")
        self.set_y(max(self.get_y(), y0 + box_h) + 0.5)
        self.ln(4)

    def emit_list(self, blk):
        ordered, items = blk["ordered"], blk["items"]
        self.ln(0.8)
        for i, item in enumerate(items, 1):
            if self.get_y() > PH - MB - 16:
                self.add_page()
            marker = f"{i}." if ordered else "\u2022"
            self.set_font("Newsreader", "B" if ordered else "", 10.5)
            self.set_text_color(*GOLD)
            self.set_x(ML + 1.5)
            self.cell(9, 5.2, marker, new_x="LEFT", new_y="TOP")
            self.set_font("Newsreader", "", 10.5)
            self.set_text_color(*INK)
            self.set_x(ML + 11)
            self.multi_cell(BODY_W - 11, 5.2, item, markdown=True, new_x="LEFT", new_y="NEXT")
            self.ln(1.3)
        self.ln(1.6)

    def emit_colophon(self, text):
        text = text.replace("About this paper ", "**About this paper**\n", 1)
        self.ln(6)
        self.rule()
        self.ln(2.5)
        self.set_font("Newsreader", "", 9)
        self.set_text_color(*MUTE)
        self.multi_cell(BODY_W, 4.6, text, markdown=True, new_x="LEFT", new_y="NEXT")


def build(blocks):
    pdf = PaperPDF()
    pdf.set_title("Core Pillars of AI-Ready Banking")
    pdf.set_author("AI-Ready Banking Series")
    pdf.set_subject("The data, delivery, and governance foundations for AI in a regulated bank.")

    pdf.add_font("Newsreader", "", ensure_ttf(""))
    pdf.add_font("Newsreader", "B", ensure_ttf("B"))
    pdf.add_font("Newsreader", "I", ensure_ttf("I"))
    pdf.add_font("NewsreaderD", "B", ensure_ttf("D"))

    # ---- cover ----
    pdf.add_page()
    pdf.set_fill_color(*NAVY)
    pdf.rect(0, 0, PW, PH, style="F")
    pdf.set_xy(24, 34)
    pdf.set_font("Newsreader", "", 11)
    pdf.set_char_spacing(1.6)
    pdf.set_text_color(*GOLD_LT)
    pdf.cell(0, 6, "WHITE PAPER  \u00b7  NO. 01")
    pdf.set_char_spacing(0)
    pdf.set_xy(24, 50)
    pdf.set_font("NewsreaderD", "B", 26)
    pdf.set_text_color(255, 255, 255)
    pdf.multi_cell(155, 13.5, "Core Pillars of\nAI-Ready Banking", new_x="LEFT", new_y="NEXT")
    pdf.set_xy(24, 98)
    pdf.set_font("Newsreader", "", 12.5)
    pdf.set_text_color(185, 199, 217)
    pdf.multi_cell(128, 7.5, "What it takes for a bank to put AI in the decision path: "
                            "one clean view of the customer, events that arrive in time, "
                            "and governance the system enforces on itself.", new_x="LEFT", new_y="NEXT")
    pdf.set_draw_color(255, 255, 255)
    pdf.line(24, PH - 46, PW - 24, PH - 46)
    pdf.set_xy(24, PH - 39)
    pdf.set_font("Newsreader", "", 9.5)
    pdf.set_text_color(147, 165, 187)
    pdf.cell(80, 6, "AI-Ready Banking Series")
    pdf.set_xy(PW - 24 - 45, PH - 39)
    pdf.cell(45, 6, "August 2026", align="R")

    # ---- content ----
    pdf.set_margins(ML, MT, MR)
    pdf.set_auto_page_break(auto=True, margin=MB + 6)
    pdf.add_page()
    for blk in blocks:
        pdf.emit(blk)

    pdf.output(OUT)
    print("wrote", OUT, os.path.getsize(OUT), "bytes,", pdf.pages_count, "pages")


if __name__ == "__main__":
    build(parse(SRC))